### ISSUE TITLE
no npm

### ISSUE THREAD

**Issue by Adrianm6254** [chazchumley/components#1]
I have just tried to install the lando container and everything went as expected until I tried to compile sass.

I changed into the sub theme directory but when I tried to run 'npm install' I got '-bash: npm: command not found'

**Comment by chazchumley** [comment]
@Adrianm6254 you need to be within the web/themes/custom/ohana directory.  That is where the package.json file is that npm requires to download dependencies.  If you are getting npm: command not found then make sure you installed nodejs on your operating system.
